from pathlib import Path
from typing import Optional

from docsync.diff.api_diff import DiffResult
from docsync.llm.client import LLMClient
from docsync.llm.prompts import README_UPDATE_SYSTEM, README_UPDATE_USER


class READMEUpdater:
    def __init__(self, llm_client: LLMClient, readme_path: Path):
        self.llm = llm_client
        self.readme_path = readme_path

    def update(self, diff_result: DiffResult, dry_run: bool = False) -> Optional[str]:
        if not diff_result.has_changes():
            print("No API changes to apply to README.")
            return None

        readme_content = self._read_current()

        changes_text = diff_result.to_text()

        user_prompt = README_UPDATE_USER.format(
            readme_content=readme_content,
            changes_text=changes_text,
        )

        print("Generating updated README via LLM...")
        result = self.llm.complete(README_UPDATE_SYSTEM, user_prompt)

        if result and not dry_run:
            self._write(result)
            print(f"Updated {self.readme_path}")
        elif result and dry_run:
            print("=== DRY RUN — README would be updated ===")

        return result

    def _read_current(self) -> str:
        if self.readme_path.exists():
            return self.readme_path.read_text(encoding="utf-8")
        return "# Project\n\n<!-- Auto-generated by DocSync -->\n"

    def _write(self, content: str):
        self.readme_path.parent.mkdir(parents=True, exist_ok=True)
        self.readme_path.write_text(content, encoding="utf-8")
